export TT_METAL_ENV="dev"
export TT_BACKEND_OPT_LEVEL=0
unset TT_METAL_LOGGER_LEVEL
unset TT_METAL_LOGGER_TYPES
unset TT_METAL_DPRINT_CHIPS
unset TT_METAL_DPRINT_CORES
export TT_METAL_HOME=$(pwd)
export PYTHONPATH=$(pwd)
export ARCH_NAME=blackhole
export VENDOR=BLACKHOLEPLUS_AS_TT

# export TT_METAL_KERNEL_READBACK_ENABLE="1"
# export TT_METAL_SLOW_DISPATCH_MODE="1"
# export TT_METAL_LOGGER_LEVEL="Debug"
# export TT_METAL_LOGGER_TYPES="All"
# export TT_METAL_DPRINT_CHIPS=0
# export TT_METAL_DPRINT_CORES=all
# export TT_METAL_DISABLE_L1_DATA_CACHE_RISCVS="BR,NC,TR,ER"
# export TT_METAL_WATCHER=120
# export TT_PCI_LOG_LEVEL=2
