import ttnn
from models.bos_model.yolov8s.configs.utils import ConcatConfig, ConvConfig, UpsampleConfig

layer_configs = {
    "model.0.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.1.conv": ConvConfig(core_end=(3, 3), shard_layout="Height", reshard_if_not_optimal=False),
    "model.2.cv1_a.conv": ConvConfig(core_end=(3, 3), shard_layout="Height", reshard_if_not_optimal=True),
    "model.2.cv1_b.conv": ConvConfig(core_end=(3, 3), shard_layout="Height", reshard_if_not_optimal=True),
    "model.2.m.0.cv1.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.2.m.0.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.2.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.3.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.4.cv1_a.conv": ConvConfig(core_end=(3, 3), shard_layout="Height", reshard_if_not_optimal=True),
    "model.4.cv1_b.conv": ConvConfig(core_end=(3, 3), shard_layout="Height", reshard_if_not_optimal=True),
    "model.4.m.0.cv1.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.4.m.0.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.4.m.1.cv1.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.4.m.1.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.4.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.5.conv": ConvConfig(core_end=(3, 3), shard_layout="Height", reshard_if_not_optimal=True),
    "model.6.cv1_a.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.6.cv1_b.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.6.m.0.cv1.conv": ConvConfig(core_end=(3, 1), shard_layout="Height"),
    "model.6.m.0.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.6.m.1.cv1.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.6.m.1.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.6.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.7.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.8.cv1_a.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.8.cv1_b.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.8.m.0.cv1.conv": ConvConfig(core_end=(3, 1), shard_layout="Height"),
    "model.8.m.0.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.8.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.9.cv1.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.9.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Block"),
    "model.10.upsample": UpsampleConfig(input_shape=[1, 512, 8, 8], shard_strategy="Height"),
    "model.11.concat": ConcatConfig(input_shape=[1, 1, 400, 768], shard_strategy="Height"),
    "model.12.cv1_a.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.12.cv1_b.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.12.m.0.cv1.conv": ConvConfig(core_end=(3, 1), shard_layout="Height"),
    "model.12.m.0.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.12.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.14.concat": ConcatConfig(input_shape=[1, 1, 1600, 384], shard_strategy="Height"),
    "model.15.cv1_a.conv": ConvConfig(core_end=(3, 3), shard_layout="Height", reshard_if_not_optimal=True),
    "model.15.cv1_b.conv": ConvConfig(core_end=(3, 3), shard_layout="Height", reshard_if_not_optimal=True),
    "model.15.m.0.cv1.conv": ConvConfig(core_end=(3, 1), shard_layout="Height"),
    "model.15.m.0.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.15.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.16.conv": ConvConfig(core_end=(3, 1), shard_layout="Height", reshard_if_not_optimal=True),
    "model.17.concat": ConcatConfig(input_shape=[1, 1, 416, 384], shard_strategy="Height"),
    "model.18.cv1_a.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.18.cv1_b.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.18.m.0.cv1.conv": ConvConfig(core_end=(3, 1), shard_layout="Height"),
    "model.18.m.0.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.18.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.19.conv": ConvConfig(core_end=(3, 3), shard_layout="Height", reshard_if_not_optimal=True),
    "model.20.concat": ConcatConfig(input_shape=[1, 1, 128, 768], shard_strategy="Height"),
    "model.21.cv1_a.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.21.cv1_b.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.21.m.0.cv1.conv": ConvConfig(core_end=(3, 1), shard_layout="Height"),
    "model.21.m.0.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.21.cv2.conv": ConvConfig(core_end=(3, 3), shard_layout="Block"),
    "model.22.cv2.0.0.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv2.0.1.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv2.0.2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv2.1.0.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv2.1.1.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv2.1.2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv2.2.0.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv2.2.1.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv2.2.2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv3.0.0.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv3.0.1.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv3.0.2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height", reshard_if_not_optimal=True),
    "model.22.cv3.1.0.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv3.1.1.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv3.1.2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv3.2.0.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv3.2.1.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    "model.22.cv3.2.2.conv": ConvConfig(core_end=(3, 3), shard_layout="Height"),
    # "model.22.concat.0.concat": ConcatConfig(input_shape=[1, 1, 1600, 144], shard_strategy="Height"),
    # "model.22.concat.1.concat": ConcatConfig(input_shape=[1, 1, 400, 144], shard_strategy="Height"),
    # "model.22.concat.2.concat": ConcatConfig(input_shape=[1, 1, 100, 144], shard_strategy="Height"),
    "model.22.concat.0.concat": None,
    "model.22.concat.1.concat": None,
    "model.22.concat.2.concat": None,
}
